Algoritmo "Exercicio-5"
// Autor(a)    : Lavínia Bueno
// Data atual  : 15/03/2022
Var
larg, comp, area :real


Inicio
Escreval("Bem vindo(a) ao Marli&Simone Negócios Imobiliarios")
Escreval("Vendemos Apenas terrenos retangulares")

Escreval(" ")
Escreval("Digite a largura do terreno: ")
Leia(larg)
Escreva("Digite o comprimento do terreno: ")
Leia(comp)
area:= larg * comp
Escreva("A área deste terreno é: ",area," m²")


Fimalgoritmo